backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: /static/media
public_folder: /media

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: blog-post }
      - { label: Title, name: title, widget: string }
      - { label: Visible, name: isShown, widget: boolean }
      - { label: Feature Image, name: featureImage, widget: image }
      - { label: Feature Image Caption, name: featureImageCaption, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list, required: false }
  - name: product
    folder: src/pages/product
    label: Product
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: product }
      - { label: Product Name, name: title, widget: string }
      - { label: Price, name: price, widget: string }
      - { label: Product Id, name: product id, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Heading, name: heading, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Tags, name: tags, widget: list }

  - name: pages
    label: Pages
    files:
      - file: src/pages/album/index.md
        label: Album
        name: album
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: album-page }
          - {
              label: Images,
              name: images,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Description, name: description, widget: text, required: false },
                  { label: Caption, name: caption, widget: string },
                  { label: Alt, name: alt, widget: string },
                  { label: Tags, name: tags, widget: list, required: false },
                ],
            }
